languageCode = "en-us"
title = "Sarai Rosenberg"
baseurl = "https://sar.ai"
theme = "prologue"

[params]
  name = "Sarai Rosenberg"
  description = "Mathematician in Product"
  copyright = "2017 Anna Sarai Rosenberg."

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "hi@sar.ai"
  
[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/Saraislet"
  
[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/@anna.sarai.rosenberg"

[[params.social]]
  medium = "codepen"
  icon = "codepen"
  link = "https://codepen.io/saraislet/"
  

# Portfolio column one

[[params.portfolio1]]
  title = "Agiloft contact entry streamlined UX"
  alt = "I streamlined Agiloft's contact entry by removing pop-up windows, and allowing the user to enter contacts into the same window seamlessly."
  source = "img/AL-contact_entry-comparison3.png"
  url = "https://medium.com/women-in-product/how-to-make-fiends-and-influence-product-cfb816d88d9c"

[[params.portfolio1]]
  title = "Guidelines for Respectful Collection of Demographic Data"
  alt = ""
  source = "img/ideal-gender3.png"
  url = "https://medium.com/shenomads/respectful-collection-of-demographic-data-56de9fcb80e2"

# Portfolio column two

[[params.portfolio2]]
  title = "Designing Products for Abuse"
  alt = "Image shows a red fractal on a white background, roughly shaped like a cradle."
  source = "img/2005-06-03-cradle2-sm2.jpg"
  url = "https://medium.com/@anna.sarai.rosenberg/designing-products-for-abuse-7d6ca583ff7a"

[[params.portfolio2]]
  title = "Facebook reaction UI suggestion"
  alt = "Facebook reactions currently replace the 'Like' text. My suggestion is to retain the old change of 'Like' to 'Unlike', and put the reaction to the right."
  source = "img/fb-command_line-suggestion.png"
  url = "https://blog.prototypr.io/ui-of-likes-on-social-media-dfcd3baa4081"

# Portfolio column 3

[[params.portfolio3]]
  title = "CodePen experiment"
  alt = "Image shows purple concentric circles connected by green lines, rotating and oscillating"
  source = "img/codevember-2016-day_11.png"
  url = "https://codepen.io/saraislet/pen/PbNovr"

[[params.portfolio3]]
  title = "Record #404"
  alt = "Image shows an error window with the message 'Record 404 not found'."
  source = "img/404-record.png"
  url = ""
